# Generated by Django 5.0.6 on 2024-08-18 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='price',
            field=models.PositiveBigIntegerField(default=400),
            preserve_default=False,
        ),
    ]
